/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.12.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package ru.yandex.practicum.eshop.payment.service.controller;

import jakarta.validation.Valid;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.server.ServerWebExchange;
import reactor.core.publisher.Mono;
import ru.yandex.practicum.eshop.payment.service.dto.CreatePaymentByCartIdResponseOk;

public interface DefaultApi {

  /**
   * POST /payment-service/buy : Создание платежа по ID корзины
   *
   * @param cartId  (required)
   * @return Заказ успешно создан (status code 200)
   */
  @RequestMapping(
      method = RequestMethod.POST,
      value = "/payment-service/buy",
      produces = {"application/json"}
  )

  default Mono<ResponseEntity<CreatePaymentByCartIdResponseOk>> createPaymentByCartId(
      @Valid @RequestParam(value = "cartId") Long cartId, ServerWebExchange exchange
  ) {
    Mono<Void> result = Mono.empty();
    exchange.getResponse().setStatusCode(HttpStatus.NOT_IMPLEMENTED);
    for (MediaType mediaType : exchange.getRequest().getHeaders().getAccept()) {
      if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
        String exampleString = "{ \"orderId\" : 0 }";
        result = ApiUtil.getExampleResponse(exchange, MediaType.valueOf("application/json"),
                                            exampleString);
        break;
      }
    }
    return result.then(Mono.empty());
  }
}