spring:
  r2dbc:
    url: r2dbc:h2:mem:///eshop;DB_CLOSE_DELAY=-1;MODE=MySQL
    username: sa
    password:

jdbc:
  driverClassName: org.h2.Driver
  url: jdbc:h2:mem:eshop;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  username: sa
  password: