ALTER TABLE cart_item DROP CONSTRAINT IF EXISTS cart_item_cart_id_fkey;
ALTER TABLE order_item DROP CONSTRAINT IF EXISTS order_item_order_id_fkey;


DROP TABLE IF EXISTS cart;
DROP TABLE IF EXISTS cart_item;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS order_item;


CREATE TABLE IF NOT EXISTS cart(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    total float8
);

CREATE TABLE IF NOT EXISTS cart_item(
     id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     cart_id bigint,
     item_id bigint,
     count   int
);

CREATE TABLE IF NOT EXISTS orders(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    total_sum float8
);

CREATE TABLE IF NOT EXISTS order_item(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id bigint,
    item_id bigint,
    count   int
);


ALTER TABLE cart_item ADD FOREIGN KEY (cart_id) REFERENCES cart (id) ON DELETE CASCADE;
ALTER TABLE order_item ADD FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE;
