server:
  port: 8080
  servlet:
    encoding:
      enabled: true
      charset: UTF-8
      force: true

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/eshop-db              # URL подключения к базе данных
    username: postgres    # Имя пользователя базы данных
    password: postgres    # Пароль пользователя
    pool:
      enabled: true                               # Включение пула соединений
      initial-size: 10                            # Начальное количество соединений в пуле
      max-size: 50                                # Максимальное количество соединений
      max-idle-time: 30s                          # Время бездействия соединения перед закрытием
      max-life-time: 10m                          # Максимальное время жизни соединения
      validation-query: SELECT 1                  # SQL-запрос для проверки работоспособности соединения
  data:
    redis:
      host: localhost
      port: 6379
  security:
    user:
      name: user
      password: password
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/master # Адрес сервера авторизации для получения токена
        registration:
          eshop: # Описание клиента OAuth2
            provider: keycloak
            authorizationGrantType: client_credentials
            client-id: eshop-core
            client-secret: 3xtyfQtqjHnuEbj0YN8M9fuVY0yPERYE
            scope: profile
            clientAuthenticationMethod: client_secret_post # Способ передачи секрета

client:
  payment-service:
    base-url: http://localhost:8081/payment-service/buy
    connect-timeout-ms: 1000
    response-timeout-ms: 1000

logging:
  level:
    org:
      springframework:
        security: DEBUG