server:
  port: 8080

spring:
  main:
    allow-bean-definition-overriding: true
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/eshop-db              # URL подключения к базе данных
    username: postgres    # Имя пользователя базы данных
    password: postgres    # Пароль пользователя
    pool:
      enabled: true                               # Включение пула соединений
      initial-size: 10                            # Начальное количество соединений в пуле
      max-size: 50                                # Максимальное количество соединений
      max-idle-time: 30s                          # Время бездействия соединения перед закрытием
      max-life-time: 10m                          # Максимальное время жизни соединения
      validation-query: SELECT 1                  # SQL-запрос для проверки работоспособности соединения
  data:
    redis:
      host: localhost
      port: 6379
  security:
    user:
      name: user
      password: password

client:
  payment-service:
    base-url: http://localhost:8081/payment-service/buy
    connect-timeout-ms: 1000
    response-timeout-ms: 1000